-- ============================================================================
-- COSMIC DEPT — seed data.
-- Run AFTER 0000_init_schema.sql (and 0001_atomic_stock.sql).
--   Supabase SQL editor: paste + run, or `supabase db reset` auto-runs this.
-- Idempotent: products upsert on slug, admin upserts on email.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- PRODUCTS (mirrors the app's built-in demo catalog)
-- ids / timestamps are generated by the table defaults.
-- ---------------------------------------------------------------------------
insert into public.products
  (name, slug, category, price, sale_price, description, short_desc, sizes, colors, badge, stock, images, is_active, is_featured)
values
  (
    'NEON CYBERPUNK DRIFTER JACKET', 'neon-cyberpunk-drifter-jacket', 'mens',
    189.99, 149.99,
    'High-visibility luminescent bomber jacket designed for cold cosmic nights. Water-resistant outer shell with interactive EL wire piping along the sleeves.',
    'Luminescent cyberpunk bomber jacket with EL wire piping.',
    array['M','L','XL'], array['#FF007F','#00F0FF','#0F0F1A'], 'HOT', 12,
    array['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80'],
    true, true
  ),
  (
    'MATRIX RETRO MONO GLASSES', 'matrix-retro-mono-glasses', 'accessories',
    45.00, null,
    'Polarized narrow frames with green grid terminal lens reflections. Full UV400 protection against high-altitude solar winds.',
    'Narrow cyberpunk sunglasses with green grid reflection.',
    array['OS'], array['#000000','#39FF14'], 'NEW', 45,
    array['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80'],
    true, true
  ),
  (
    'LUSAKA SHADOW SECURITY HOODIE', 'lusaka-shadow-security-hoodie', 'gym',
    79.99, 59.99,
    'Heavyweight loopback cotton construction engineered by Shadow Root Security Technologies. Includes an integrated RFID-blocking stealth pocket.',
    'Heavyweight tactical hoodie with integrated RFID-blocking pocket.',
    array['S','M','L','XL','XXL'], array['#0A0812','#2A1F45'], 'LIMITED', 3,
    array['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80'],
    true, false
  ),
  (
    'ORBITAL AMULET COLLAR', 'orbital-amulet-collar', 'jewelry',
    120.00, null,
    'Polished titanium hardware suspended from a dark energy synthetic cord. Houses a glowing synthetic emerald center stone.',
    'Titanium orbital amulet with synthetic glowing emerald.',
    array['OS'], array['#B68D40','#39FF14'], 'SALE', 18,
    array['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80'],
    true, true
  ),
  (
    'COSMIC RUNNER V1', 'cosmic-runner-v1', 'gym',
    150.00, null,
    'Aerodynamic mesh runners featuring gold-flecked synthetic leather reinforcement. Custom rubber grip pads matching space gravity standards.',
    'Gold-accented aerospace-grade training running shoes.',
    array['8','9','10','11'], array['#FFFFFF','#B68D40'], '', 0,
    array['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80'],
    true, false
  ),
  (
    'ZERO-G AURORA SLIP DRESS', 'zero-g-aurora-slip-dress', 'womens',
    135.00, 99.00,
    'Iridescent bias-cut slip that shifts hue with the light, woven from recycled orbital-grade satin. Built for low-gravity soirées and deep-space galleries.',
    'Iridescent hue-shifting satin slip dress.',
    array['XS','S','M','L'], array['#C0B5FF','#9B6DFF'], 'NEW', 20,
    array['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&auto=format&fit=crop&q=80'],
    true, true
  )
on conflict (slug) do nothing;

-- ---------------------------------------------------------------------------
-- ADMIN AUTHORIZATION ALLOWLIST
-- NOTE: this only authorizes the email. You must ALSO create the matching
-- Supabase Auth user (Dashboard → Authentication → Add user, or sign-up) with
-- the same email + a password. Change the email below to your operator.
-- ---------------------------------------------------------------------------
insert into public.admin_users (email, role)
values ('uchichinyama@gmail.com', 'super_admin')
on conflict (email) do nothing;
